services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      #local dir/files: docker dir/files
      # iOS
      # - /Users/Admin/Documents/research_automation_platform/docker-volume/mongo_db:/data/db
      # - /Users/Admin/Documents/research_automation_platform/docker-volume/backup:/backup
      # Windows
      #- /c/Users/Admin/Documents/research_automation_platform/docker-volume/mongo_db:/data/db
      #- /c/Users/Admin/Documents/research_automation_platform/docker-volume
      # Linux
      - /home/emran/devspace/research_automation_platform/docker-volume/mongo_db:/data/db
      - /home/emran/devspace/research_automation_platform/docker-volume/backup:/backup
    ports:
      - 27017:27017
      # networks:
      # - mongo
      #echo 'db.runCommand("ping").ok' | mongo 10.10.10.60:27017/test --quiet

  mongo-express:
    image: mongo-express:latest
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      #- ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=root
    volumes:
      # - /c/Users/Admin/Documents/research_automation_platform/docker-volume/mongo_db
      # Linux
      - /home/emran/devspace/research_automation_platform/docker-volume/mongo_db:/data/db
    ports:
      - 8081:8081
    links:
      - mongodb
    # wget --quiet --tries=3 --spider http://admin:admin123@10.10.10.60:8081 || exit 1

    # networks:
    # mongo: # docker-compose-files_mongo
    # driver: bridge
    # networks: -- To use above network services in other projects add this networks property
    #  docker-compose-files_mongo: -- {{directory_name}}_{{network_name}}
    #    external: true -- are you using external network?
